version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: assignment_db
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "purchases:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  server_api:
    build:
      context: api_server_customer_management
      dockerfile: Dockerfile
    container_name: api_server_customer_management
    ports:
      - "6201:8000"
    depends_on:
      - kafka
      - mongo
    restart: unless-stopped
    environment:
      MONGO_DB_URL: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017"
      MONGO_DB_NAME: "assignment_db"
      KAFKA_BROKERS: "[\"kafka:9092\"]"
      KAFKA_TOPIC: "purchases"
      KAFKA_CONSUMER: "consumer"

  customers_api:
    build:
      context: customer_facing_web_server
      dockerfile: Dockerfile
    container_name: customers_api
    ports:
      - "6200:8000"
    depends_on:
      - kafka
      - server_api
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: "[\"kafka:9092\"]"
      KAFKA_TOPIC: "purchases"
      MANAGING_API_URL: "http://api_server_customer_management:6201"